version: "3"
services:

  tempo:
    image: grafana/tempo:1.4.1
    command: [ "-search.enabled=true", "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./overrides.yaml:/etc/overrides.yaml
    ports:
      - "3200:3200"   # tempo
      - "14268"  # jaeger ingest
      - "4317" # otlp gRPC ingest

#  Commenting out because Grafana UI has search enabled. Uncomment if you want to use the Jaeger UI!
#
#  tempo-query:
#    image: grafana/tempo-query:latest
#    command: [ "--grpc-storage-plugin.configuration-file=/etc/tempo-query.yaml" ]
#    volumes:
#      - ./tempo-query.yaml:/etc/tempo-query.yaml
#    ports:
#      - "16686:16686"  # jaeger-ui
#    depends_on:
#      - tempo

  itchysats-testnet:
    image: ghcr.io/itchysats/itchysats/taker:master
    restart: on-failure
    environment:
      - RUST_LOG="opentelemetry"
    ports:
      - 8000:8000
    volumes:
      - ./data:/data
    command: |
      --log-level=Debug
      --instrumentation
      --collector-endpoint="http://tempo:4317"
      testnet

  prometheus:
    image: prom/prometheus:latest
    command: [ "--config.file=/etc/prometheus.yaml" ]
    volumes:
      - ../shared/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:9.0.5   # track main as search is under active development
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
